version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - 3001:8000
      - 5555:5555
    environment:
      - DATABASE_URL=file:./dev.db
      - LOCALSTACK_HOST=localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  localstack:
    container_name: 'localstack'
    image: localstack/localstack:3.2
    ports:
      - '4566:4566'
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=dynamodb,sqs
